#################################################### deploy - templates

.deploy-template:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/.terraform
    TF_VAR_image: $CI_REGISTRY_IMAGE
    TF_VAR_image_version: $CI_COMMIT_SHORT_SHA
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}
  before_script:
    - cd ${TF_ROOT}
    - gitlab-terraform init
    - gitlab-terraform validate
